#!/bin/bash

# DO NOT FORGET TO MODIFY /etc/hosts
domain="your_domain.com"
action="$1"
choice="$2"
arg="$3"
arg2="$4"
arg3="$5"
arg4="$6"
arg5="$7"
add_flag="$#"
path="./"
path_auth="./auth"
cookie="./auth/happy_cookie.txt"
log_auth="./auth/auth.log"
logs_e="./logs/errors.log"
doc="./source/doc.txt"